firewall/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

old/firewall/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_security import UserMixin, RoleMixin

db = SQLAlchemy()


roles_users = db.Table('roles_users', 
                       db.Column('user_id', db.Integer(), db.ForeignKey('users.id')),
                       db.Column('role_id', db.Integer(), db.ForeignKey('roles.id')))


class Manpages(db.Model):
    __tablename__ = "manpages"

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    available = db.Column(db.Boolean())
    created = db.Column(db.DateTime())
    last_update = db.Column(db.DateTime())

    def __init__(self, name, created):
        self.name = name
        self.created = created

    def __repr__(self):
        return "<Manpages %r>" % (self.name)


class Role(db.Model, RoleMixin):
    __tablename__ = "roles"

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return '<Role %r>' % (self.name)


class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), unique=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    last_login = db.Column(db.DateTime())
    created = db.Column(db.DateTime())
    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))

    def __init__(self, username, email, password, active, created, roles):
        self.username = username
        self.email = email
        self.password = password
        self.active = active
        self.created = created
        self.roles = roles

    def __repr__(self):
        return '<User %r>' % (self.username)

old/firewall/views/api.py
from flask import Blueprint, jsonify, request, abort

from firewall.dashboard.shorewall import get_config_data, get_config_files
from firewall.dashboard.shorewall import (get_rule_data, create_rule_config, 
        save_rule_config, save_config_data, rename_rule_config, 
        delete_rule_config)
from firewall.dashboard.system import meminfo, do_action


# create a blueprint
api = Blueprint('api', __name__)

api_version = "1.0"

# creata a dict for api specific error messages to return in json format
errors = {
    400: {
        "method": "BAD REQUEST",
        "message": "Bad Request",
        "status": 400,
    },
    405: { 
        "method": "METHOD NO ALLOWED",
        "message": "The method is not allowed for the requested URL.",
        "status": 405,
    },
    404: {
        "method": "NOT Found",
        "message": "Not found",
        "status": 404,
    },
    500: {
        "method": "INTERAL SERVER ERROR",
        "message": "Internal server error occurs",
        "status": 500,
    },
}

@api.app_errorhandler(400)
def error_bad_request(error):
    return jsonify(errors[400]), 400

@api.app_errorhandler(405)
def error_method_not_allowed(error):
    return jsonify(errors[405]), 405

@api.app_errorhandler(404)
def error_not_found(error):
    return jsonify(errors[404]), 404

@api.app_errorhandler(401)
def error_forbidden(error):
    return jsonify(errors[401]), 401

@api.app_errorhandler(500)
def error_internal_error(error):
    return jsonify(errors[500]), 500


### start public api_version 1.0 ###
## config ##
@api.route("/%s/config/" % api_version, methods=["GET"])
def api_get_config_files():
    return jsonify(get_config_files())

@api.route("/%s/config/<string:file_id>" % api_version, methods=["GET"])
def api_get_config_data(file_id):
    return jsonify(get_config_data(file_id))

@api.route("/1.0/config/<string:file_id>", methods=["PUT"])
def api_save_config_data(file_id):
    if request.json:
        return jsonify(save_config_data(file_id, request.json)), 201
    else:
        return error_bad_request(400)

## rule ##
#@api.route("/%s/rule/" % api_version, methods=["GET"])
#def api_get_rules():
#    return jsonify(get_rules());

@api.route("/1.0/rule/<string:zone_id>/<string:file_id>", methods=["GET"])
def api_get_rule_data(zone_id, file_id):
    return jsonify(get_rule_data(zone_id, file_id))

@api.route("/1.0/rule/<string:zone_id>/<string:file_id>", methods=["POST"])
def api_create_rule_config(zone_id, file_id):
    return jsonify(create_rule_config(zone_id, file_id)), 201

@api.route("/1.0/rule/<string:zone_id>/<string:file_id>", methods=["DELETE"])
def api_delete_rule_config(zone_id, file_id):
    return jsonify(delete_rule_config(zone_id, file_id)), 201

@api.route("/1.0/rule/<string:zone_id>/<string:file_id>/<string:new_file_id>", methods=["PUT"])
def api_rename_rule_config(zone_id, file_id, new_file_id):
    return jsonify(rename_rule_config(zone_id, file_id, new_file_id)), 201

@api.route("/1.0/rule/<string:zone_id>/<string:file_id>", methods=["PUT"])
def api_save_rule_config(zone_id, file_id):
    if request.json:
        return jsonify(save_rule_config(zone_id, file_id, request.json)), 201
    else:
        return error_bad_request(400)


## setting ##

## system ##
@api.route("/1.0/system/meminfo", methods=["GET"])
def api_system_meminfo():
    return jsonify(meminfo())

## action ##
@api.route("/1.0/action/<string:action_id>", methods=["POST"])
def api_action(action_id):
    # in static/js/firewall.js do_action() add too to disabeled buttons
    allowed_action = ["start", "stop", "restart", "clear", "reload", "check",
        "status"]
    if action_id in allowed_action:
        return jsonify(do_action(action_id))
    else:
        return error_bad_request(400)

old/firewall/views/dashboard.py
from flask import Blueprint, render_template
from flask_security import current_user

from firewall.dashboard.system import uptime, meminfo
from firewall.dashboard.shorewall import (get_rules, get_config_files, 
        get_config)

dashboard = Blueprint('dashboard', 
                      __name__,
                      template_folder="template",
                      static_folder=None)


@dashboard.route('/')
def index():
    print(current_user.last_login)
    data = {
        "last_login": current_user.last_login,
        "uptime": uptime(),
        "meminfo": meminfo(),
    }
    return render_template("dashboard/index.html", data=data)

@dashboard.route('/Configs', methods=["GET"])
def firewall_configs():
    data = get_config_files()
    return render_template("dashboard/firewall-configs.html")

@dashboard.route('/Rules', methods=["GET"])
def firewall_rules():
    data = get_rules()
    return render_template("dashboard/firewall-rules.html", data=data)

@dashboard.route('/Settings', methods=["GET"])
def firewall_settings():
    data = {
        "interfaces": get_config("interfaces"),
        "zones": get_config("zones"),
    }
    return render_template("dashboard/firewall-settings.html", data=data)

@dashboard.route('/Action', methods=["GET"])
def firewall_action():
    return render_template("dashboard/firewall-action.html")

@dashboard.route('/Info', methods=["GET"])
def firewall_info():
    return render_template("dashboard/firewall-info.html")

old/firewall/views/home.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder="templates")


@main.route('/')
def index():
    return "Main"

old/firewall/templates/dashboard/firewall-action.html
{% extends 'layout.html' %}
{% block css %}
{% endblock %}
{% block navigation %}
  {% include "dashboard/navigation.html" %}
{% endblock %}
{% block container %}
<div class="row">
  <div class="col-md-3">
    <p>{{ _("Choose an action to perform:") }}</p>
  </div>
  <div class="col-md-9">
    <div class="btn-group" id="action-click">
      <button type="button" class="btn btn-default" id="action-start">
        {{ _("Start") }}
      </button>
      <button type="button" class="btn btn-default" id="action-stop">
        {{ _("Stop") }}
      </button>
      <button type="button" class="btn btn-default" id="action-reload">
        {{ _("Reload") }}
      </button>
      <button type="button" class="btn btn-default" id="action-restart">
        {{ _("Restart") }}
      </button>
      <button type="button" class="btn btn-default" id="action-clear">
        {{ _("Clear") }}
      </button>
      <button type="button" class="btn btn-default" id="action-check">
        {{ _("Check") }}
      </button>
      <button type="button" class="btn btn-default" id="action-status">
        {{ _("Status") }}
      </button>
    </div>
  </div>
</div>
<hr class="style-one">
<div id="spinner">
  <button class="btn btn-lg btn-info">
    <span class="glyphicon glyphicon-refresh spinning"></span>{{ _("Loading...") }}
  </button>
</div>
<div class="info-box fade in"></div>
{% endblock %}

old/firewall/templates/dashboard/firewall-configs.html
{% extends 'layout.html' %}
{% block css %}
{% endblock %}
{% block navigation %}
  {% include "dashboard/navigation.html" %}
{% endblock %}
{% block container %}
{% include "dashboard/modal-rules.html" %}
<p>{{ _("Choose a file to modify") }}</p>
<div class="info-box"></div>
<hr class="style-one">
  <div class="list-group edit-config" id="configs"> 
  </div>
{% endblock %}

old/firewall/templates/dashboard/firewall-info.html
{% extends 'layout.html' %}
{% block css %}
{% endblock %}
{% block navigation %}
  {% include "dashboard/navigation.html" %}
{% endblock %}
{% block container %}
<div class="info-box"></div>
{% endblock %}

old/firewall/templates/dashboard/firewall-rules.html
{% extends 'layout.html' %}
{% block css %}{% endblock %}
{% block navigation %}
{% include "dashboard/navigation.html" %}
{% endblock %}
{% block container %}
{% include "dashboard/modal-rules.html" %}
{% if data.error %}
  <div class="alert alert-danger">
    {{ data.error }}
  </div>
{% else %}

<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-9">

    <div class="btn-group" id="modus-click">
      <button type="button" class="btn btn-default" id="modus-edit">
        {{ _("Edit") }}
      </button>
      <button type="button" class="btn btn-default" id="modus-rename"> 
        {{ _("Rename") }}
      </button>
      <div class="btn-group">
        <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle"
          id="modus-create">
          {{ _("Create") }} 
          <span class="glyphicon glyphicon-collapse-down"></span>
        </button>
        <ul class="dropdown-menu">
        {% for zone in data.data.keys()|sort %}
          <li><a href="#{{ zone }}" data-zone-id="{{ zone }}"
                class="create-config">Zone: {{ zone }}</a></li>
        {% endfor %}
       </ul>
      </div>
      <button type="button" class="btn btn-default" id="modus-delete"> 
        {{ _("Delete") }}
      </button>

     </div>

  </div>
</div>

<div class="row" style="display: none"> 
  <div class="col-sm-3">
    <span data-toggle="tooltip" title="{{ _("Plain is using textarea for edit the config directly. 
    Complex is using a construction.") }}" data-placement="top">
    {{ _("Edit-Mode ") }}</span>
  </div>
  <div class="col-sm-9">
      <div class="btn-group btn-group-xs" data-toggle="buttons">
        <label class="btn btn-primary active">
          <input type="radio" id="radio-plain" name="radio-1" checked>Plain
        </label>
        <label class="btn btn-primary">
          <input type="radio" id="radio-complex" name="radio-1">Complex
        </label>
      </div>
  </div>
</div>

<hr class="style-one" id="rules-top">
 
{% for zone in data.data.keys()|sort %}
<div class="row">
  <div class="col-sm-3">
      <button class="btn btn-primary btn-block" data-toggle="collapse"
          data-target="#toggle-{{ zone }}" style="text-align:left">
            <span style="float:left">
            {{ _("Zone") }}: {{ zone }}
            </span>
            <span class="badge" id="count-{{ zone }}" style="float:right; margin-top:2px;">{{ data.data[zone]|length }}
            </span>
      </button>
  </div>
  <div class="col-sm-9">
    <div class="collapse list-group edit-config" id="toggle-{{ zone }}">
        {% for config in data.data[zone]|sort %}
              <a href="#" class="list-group-item"
                data-zone-id="{{ zone }}" data-file-id="{{ config[0] }}"
                data-hash-id="{{ config[1] }}" id="{{ config[1] }}"> {{ config[0] }}
              </a>
        {% endfor %}
    </div>
  </div>
</div>
{% endfor %}

{% endif %}
{% endblock %}

old/firewall/templates/dashboard/firewall-settings.html
{% extends 'layout.html' %}
{% block css %}{% endblock %}
{% block navigation %}
{% include "dashboard/navigation.html" %}
{% endblock %}
{% block container %}
{% include "dashboard/modal-settings.html" %}
<hr class="style-one" id="rules-top">

{% for key in data|sort %}
<div class="row">
  <div class="col-sm-3">
     {{ _(key)|capitalize}}
  </div>
  <div class="col-sm-9">
    {% if data[key].error %}
      <div class="alert alert-danger">
        {{ data[key].error }}
      </div>
    {% else %}

    <div class="list-group"> 
      <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover table-condensed">
          <thead>
            <tr> 
            {% for i in data[key].data.header.values() %}
              <th>{{ i.name|capitalize_words(split_by="_") }}</th>
            {% endfor %}
            </tr>
          </thead>
          <tbody> 
          {% for i, value in data[key].data.items() %}
            {% if i != "header" %}
            <tr>
              {% for j, header in data[key].data.header.items() %}
                {% if i != "header" %}
                <td>{{ value[header.name] }}</td>
                {% endif %}
              {% endfor %}
            </tr>
            {% endif %}
          {% endfor %}
          </tbody>
        </table>
      </div>

    </div>
    {% endif %} 
  </div>
</div>
{% endfor %}
{% endblock %}

old/firewall/templates/dashboard/index.html
{% extends 'layout.html' %}
{% block css %}{% endblock %}
{% block navigation %}
  {% include "dashboard/navigation.html" %}
{% endblock %}
{% block container %}
{% include "dashboard/modal-index.html" %}
<div class="row">
  <div class="col-sm-3">
       {{ _("last login") }}
  </div>
  <div class="col-sm-9">
    {{ data.last_login|datetime }}
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
       {{ _("uptime") }}
  </div>
  <div class="col-sm-9">
    {{ data.uptime.data }}
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
       <a href="#meminfo-all" class="meminfo">{{ _("meminfo") }}</a>
  </div>
  <div class="col-sm-9">
    <table class="table table-bordered table-striped table-responsive">
        <tr>
          <td>{{ _("MemTotal") }}</td>
          <td>{{data.meminfo.data["MemTotal"].value}}</td>
          <td>{{data.meminfo.data["MemTotal"].unit}}</td>
        </tr>
        <tr>
          <td>{{ _("MemFree") }}</td>
          <td>{{data.meminfo.data["MemFree"].value}}</td>
          <td>{{data.meminfo.data["MemFree"].unit}}</td>
        </tr>
    </table>
  </div>
</div>
{% endblock %}

old/firewall/templates/dashboard/modal-index.html
<div id="modal-meminfo" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">{{ _("meminfo") }}: <span class="read-from"></span></h4>
          <div class="info-box"></div>
      </div>
      
      <div class="modal-body">
        <table class="table table-bordered table-striped table-responsive table-condensed">
          <tbody></tbody>
        </table>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{{ _("Close") }}</button>
      </div>
    
    </div>
  </div>
</div>

old/firewall/templates/dashboard/modal-rules.html
<div id="modal-edit" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">{{ _("Edit config: ") }} </h4>
          <div class="info-box"></div>
      </div>
      
      <div class="modal-body">
         <textarea class="form-control" id="edit-config"></textarea>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{{ _("Close") }}</button>
        <button type="button" class="btn btn-primary" id="save-config">{{ _("Save changes") }}</button>
      </div>
    
    </div>
  </div>
</div>

<div id="modal-create" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{{ _("Config name for zone: ") }}</h4>
        <p>{{ _("Config name should just a name that describe the content without suffix.") }}</p>
        <p>{{ _("Example: myTor becomes myTor.rules") }}</p>
        <p class="info-box"></p>
      </div>
      <div class="modal-body">
        <input type="text" class="form-control required" id="config-name-create" placeholder="Configname" 
          title="myService" pattern="\w+" required minlength="3">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default reset-input">{{ _("Reset") }}</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">{{ _("Close") }}</button>
        <button type="button" class="btn btn-primary" id="create-config">{{ _("Create config") }}</button>
      </div>
    </div>
 </div>
</div>

<div id="modal-rename" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{{ _("Rename config: ") }}</h4>
        <p>{{ _("Config name should just a name that describe the content without suffix.") }}</p>
        <p>{{ _("Example: myTor becomes myTor.rules") }}</p>
        <p class="info-box"></p>
      </div>
      <div class="modal-body">
        <input type="text" class="form-control required" id="config-name-rename" placeholder="Configname" 
          title="myService" pattern="\w+" required minlength="3">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default reset-input">{{ _("Reset") }}</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">{{ _("Close") }}</button>
        <button type="button" class="btn btn-primary" id="rename-config">{{ _("Rename config") }}</button>
      </div>
    </div>
 </div>
</div>

<div id="modal-delete" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{{ _("Delete config: ") }}</h4>
        <p>{{ _("You want delete this Config?") }}</p>
        <p class="info-box"></p>
      </div>
      <div class="modal-body">
        <input type="text" class="form-control" disabled id="config-name-delete"> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{{ _("Close") }}</button>
        <button type="button" class="btn btn-primary" id="delete-config">{{ _("Delete config") }}</button>
      </div>
    </div>
 </div>
</div>

old/firewall/templates/dashboard/modal-settings.html
<div id="modal-edit" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">{{ _("Edit config: ") }} </h4>
          <div class="info-box"></div>
      </div>
      
      <div class="modal-body">
         <textarea class="form-control" id="edit-config"></textarea>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{{ _("Close") }}</button>
        <button type="button" class="btn btn-primary" id="save-config">{{ _("Save changes") }}</button>
      </div>
    
    </div>
  </div>
</div>

<div id="modal-create" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{{ _("Config name for zone: ") }}</h4>
        <p>{{ _("Config name should just a name that describe the content without suffix.") }}</p>
        <p>{{ _("Example: myTor becomes myTor.rules") }}</p>
        <p class="info-box"></p>
      </div>
      <div class="modal-body">
        <input type="text" class="form-control required" id="config-name-create" placeholder="Configname" 
          title="myService" pattern="\w+" required minlength="3">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default reset-input">{{ _("Reset") }}</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">{{ _("Close") }}</button>
        <button type="button" class="btn btn-primary" id="create-config">{{ _("Create config") }}</button>
      </div>
    </div>
 </div>
</div>

<div id="modal-rename" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{{ _("Rename config: ") }}</h4>
        <p>{{ _("Config name should just a name that describe the content without suffix.") }}</p>
        <p>{{ _("Example: myTor becomes myTor.rules") }}</p>
        <p class="info-box"></p>
      </div>
      <div class="modal-body">
        <input type="text" class="form-control required" id="config-name-rename" placeholder="Configname" 
          title="myService" pattern="\w+" required minlength="3">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default reset-input">{{ _("Reset") }}</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">{{ _("Close") }}</button>
        <button type="button" class="btn btn-primary" id="rename-config">{{ _("Rename config") }}</button>
      </div>
    </div>
 </div>
</div>

<div id="modal-delete" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{{ _("Delete config: ") }}</h4>
        <p>{{ _("You want delete this Config?") }}</p>
        <p class="info-box"></p>
      </div>
      <div class="modal-body">
        <input type="text" class="form-control" disabled id="config-name-delete"> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{{ _("Close") }}</button>
        <button type="button" class="btn btn-primary" id="delete-config">{{ _("Delete config") }}</button>
      </div>
    </div>
 </div>
</div>

old/firewall/templates/dashboard/navigation.html
<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#firewall-navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('dashboard.index') }}" title="{{ _("Home") }}">
      <span class="glyphicon glyphicon-home"></span></a>
  </div>
  <div class="collapse navbar-collapse" id="firewall-navbar">
    <ul class="nav navbar-nav">
      <li><a class="navbar-brand" href="{{ url_for('dashboard.firewall_configs') }}">{{ _('Configs') }}</a></li>
      <li><a class="navbar-brand" href="{{ url_for('dashboard.firewall_rules') }}">{{ _('Rules') }}</a></li>
      <li><a class="navbar-brand" href="{{ url_for('dashboard.firewall_settings') }}">{{ _("Settings") }}</a></li>
      <li><a class="navbar-brand" href="{{ url_for('dashboard.firewall_action') }}">{{ _("Action") }}</a></li>
      <li><a class="navbar-brand" href="{{ url_for('dashboard.firewall_info') }}">{{ _("Info") }}</a></li>
</ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
        <li><a href="{{ url_for('security.logout') }}"><span class="glyphicon glyphicon-log-out"></span></a></li>
      {% endif %}
    </ul>
  </div>
</div>
</nav>

old/firewall/templates/index.html
{% extends 'layout.html' %}
{% block container %}
  <div class="top-pad">
    {{ _('Index') }}
  </div>
{% endblock %}

old/firewall/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initialscale=1">
    <title>Firewall</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet">
  {% block css %}{% endblock %}
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='favicon.ico') }}" rel="shortcut icon">
  </head>
  <body>
    {% block navigation %}
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" 
                data-target="#firewall-navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="firewall-navbar-collapse">
            <ul class="nav navbar-nav navbar-left">
              <li><a class="navbar-brand" href="{{ url_for('home') }}">{{ _('Home') }}</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li><a href="{{ url_for('security.logout') }}"><span class="glyphicon glyphicon-log-out"></span> {{ _('Log Out') }}</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    {% endblock %}

    <div class="container-fluid">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <ul class="flashes">
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
            </ul><br/>
          {% endif %}
        {% endwith %}
      {% block container %}{% endblock %}
    </div>
    <script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/firewall.js') }}"></script>
    {% block js %}{% endblock %}
  </body>
</html>

old/firewall/templates/security/_macros.html
{% macro render_field_with_errors(field) %}
  <p>
    {{ field.label }} {{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul>
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  </p>
{% endmacro %}

{% macro render_field(field) %}
  <p>{{ field(**kwargs)|safe }}</p>
{% endmacro %}

old/firewall/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <ul class="flashes">
    {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{%- endwith %}